// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClptgS_W6Po2bVQbMb_RPcU5_Ni8OSVuM',
    appId: '1:109006653809:web:3db780ed6b99bac3158ed0',
    messagingSenderId: '109006653809',
    projectId: 'tunzapresha',
    authDomain: 'tunzapresha.firebaseapp.com',
    storageBucket: 'tunzapresha.appspot.com',
    measurementId: 'G-MX0QLP10BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvSBtCJXAPXssXdspbFB1mwHbCRuUxh0Q',
    appId: '1:109006653809:android:f6b1a1b703598931158ed0',
    messagingSenderId: '109006653809',
    projectId: 'tunzapresha',
    storageBucket: 'tunzapresha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQR_gaD6BCpoGtUny9DedQ6JucXAuJKuQ',
    appId: '1:109006653809:ios:b64cb857e23617cf158ed0',
    messagingSenderId: '109006653809',
    projectId: 'tunzapresha',
    storageBucket: 'tunzapresha.appspot.com',
    iosBundleId: 'com.example.tunzaPresha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQR_gaD6BCpoGtUny9DedQ6JucXAuJKuQ',
    appId: '1:109006653809:ios:b64cb857e23617cf158ed0',
    messagingSenderId: '109006653809',
    projectId: 'tunzapresha',
    storageBucket: 'tunzapresha.appspot.com',
    iosBundleId: 'com.example.tunzaPresha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClptgS_W6Po2bVQbMb_RPcU5_Ni8OSVuM',
    appId: '1:109006653809:web:4fba16dea98f17ad158ed0',
    messagingSenderId: '109006653809',
    projectId: 'tunzapresha',
    authDomain: 'tunzapresha.firebaseapp.com',
    storageBucket: 'tunzapresha.appspot.com',
    measurementId: 'G-9QM1Y6K2EH',
  );
}
